import type {
  ConformanceCase,
  ConformanceExpectation,
} from "./schema.js";

const values = {
  privateKey: [
    "-----BEGIN PRIVATE KEY-----",
    "U1lOVEhFVElDX1JFVk9LRURfQ09ORk9STUFOQ0U=",
    "-----END PRIVATE KEY-----",
  ].join("\n"),
  aws: `AKIA${"SYNTHETICEXAMPLE"}`,
  github: `ghp_${"SYNTHETICREVOKED".padEnd(36, "0")}`,
  gitlab: "glpat-SYNTHETIC_REVOKED_GITLAB_TOKEN",
  openai: "sk-proj-SYNTHETIC_REVOKED_CONFORMANCE_KEY",
  anthropic: "sk-ant-api03-SYNTHETIC_REVOKED_CONFORMANCE_KEY",
  shopify: "shpat_SYNTHETIC_REVOKED_SHOPIFY_TOKEN",
  vault: "hvs.SYNTHETIC_REVOKED_VAULT_TOKEN",
  jwt: [
    "eyJTWU5USEVUSUNfSEVBREVS",
    "eyJTWU5USEVUSUNfUEFZTE9BRA",
    "SYNTHETIC_REVOKED_SIGNATURE",
  ].join("."),
  bearer: "SYNTHETIC_REVOKED_BEARER_VALUE",
  connectionPassword: "SYNTHETIC_REVOKED_DB_VALUE",
  encodedConnectionPassword: "SYNTHETIC%40REVOKED%3ADB%2FVALUE",
  contextual: "SYNTHETIC_REVOKED_CONTEXT_VALUE",
} as const;

function one(
  input: string,
  matched: string,
  expectation: Omit<ConformanceExpectation, "start" | "end">,
): readonly ConformanceExpectation[] {
  const start = input.indexOf(matched);
  if (start < 0) throw new TypeError("Invalid conformance fixture construction.");
  return [{ ...expectation, start, end: start + matched.length }];
}

const awsOverlap = `api_key=${values.aws}`;
const privateKeyOverlap = `private_key=${values.privateKey}`;
const githubOverlap = `access_token=${values.github}`;
const gitlabOverlap = `access_token=${values.gitlab}`;
const openAiOverlap = `client_secret=${values.openai}`;
const anthropicOverlap = `api_key=${values.anthropic}`;
const shopifyOverlap = `access_token=${values.shopify}`;
const vaultOverlap = `client_secret=${values.vault}`;
const jwtOverlap = `Authorization: Bearer ${values.jwt}`;
const connectionOverlap =
  `password=postgres://fixture:${values.connectionPassword}@localhost/db`;

export const conformanceCorpus: readonly ConformanceCase[] = [
  {
    id: "private-key-positive",
    detector: "private-key",
    kind: "positive",
    support: "supported",
    input: values.privateKey,
    expected: one(values.privateKey, values.privateKey, {
      detector: "private-key", type: "private_key", confidence: "high",
      specificity: "private-key",
    }),
    note: "Complete synthetic PEM block is supported.",
  },
  {
    id: "private-key-negative-public",
    detector: "private-key",
    kind: "negative",
    support: "supported",
    input: "-----BEGIN PUBLIC KEY-----",
    expected: [],
    note: "Public-key headers are an explicit non-secret exclusion.",
  },
  {
    id: "private-key-boundary-truncated",
    detector: "private-key",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "-----BEGIN PRIVATE KEY-----\nSYNTHETIC_TRUNCATED",
    expected: [],
    note: "Incomplete blocks are ignored to preserve precision.",
  },
  {
    id: "private-key-overlap-context",
    detector: "private-key",
    kind: "overlap",
    support: "supported",
    input: privateKeyOverlap,
    expected: one(privateKeyOverlap, values.privateKey, {
      detector: "private-key", type: "private_key", confidence: "high",
      specificity: "private-key",
    }),
    note: "Complete PEM evidence wins over a contextual name candidate.",
  },
  {
    id: "private-key-adversarial-incomplete",
    detector: "private-key",
    kind: "adversarial",
    support: "supported",
    input: `-----BEGIN PRIVATE KEY-----\n${"A".repeat(100_000)}`,
    expected: [],
    note: "A long missing footer must terminate without a finding.",
  },
  {
    id: "aws-positive-akia",
    detector: "aws-access-key",
    kind: "positive",
    support: "supported",
    input: values.aws,
    expected: one(values.aws, values.aws, {
      detector: "aws-access-key", type: "aws_access_key_id", confidence: "high",
      specificity: "provider",
    }),
    note: "The fixed-length AKIA family is supported.",
  },
  {
    id: "aws-negative-role-id",
    detector: "aws-access-key",
    kind: "negative",
    support: "supported",
    input: "AROASYNTHETICEXAMPLE",
    expected: [],
    note: "AWS role identifiers are not credentials.",
  },
  {
    id: "aws-boundary-embedded",
    detector: "aws-access-key",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: `X${values.aws}Y`,
    expected: [],
    note: "Provider values embedded in identifiers are excluded.",
  },
  {
    id: "aws-overlap-context",
    detector: "aws-access-key",
    kind: "overlap",
    support: "supported",
    input: awsOverlap,
    expected: one(awsOverlap, values.aws, {
      detector: "aws-access-key", type: "aws_access_key_id", confidence: "high",
      specificity: "provider",
    }),
    note: "Provider evidence wins over a contextual assignment.",
  },
  {
    id: "aws-adversarial-long-suffix",
    detector: "aws-access-key",
    kind: "adversarial",
    support: "supported",
    input: `AKIA${"A".repeat(100_000)}`,
    expected: [],
    note: "An overlong identifier-like suffix is rejected in bounded time.",
  },
  {
    id: "github-positive-classic",
    detector: "github-token",
    kind: "positive",
    support: "supported",
    input: values.github,
    expected: one(values.github, values.github, {
      detector: "github-token", type: "github_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A fixed-length classic token shape is supported.",
  },
  {
    id: "github-negative-test-id",
    detector: "github-token",
    kind: "negative",
    support: "supported",
    input: "SYNTHETIC_TEST_IDENTIFIER_987654321",
    expected: [],
    note: "Generic test identifiers are not provider tokens.",
  },
  {
    id: "github-boundary-short",
    detector: "github-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "ghp_SYNTHETICSHORT",
    expected: [],
    note: "Abbreviated examples are deliberately ignored.",
  },
  {
    id: "github-overlap-context",
    detector: "github-token",
    kind: "overlap",
    support: "supported",
    input: githubOverlap,
    expected: one(githubOverlap, values.github, {
      detector: "github-token", type: "github_token", confidence: "high",
      specificity: "provider",
    }),
    note: "Provider evidence wins over an access-token assignment.",
  },
  {
    id: "github-adversarial-long-suffix",
    detector: "github-token",
    kind: "adversarial",
    support: "supported",
    input: `ghp_${"A".repeat(100_000)}`,
    expected: [],
    note: "An overlong token-like identifier is rejected in bounded time.",
  },
  {
    id: "gitlab-positive-personal-access",
    detector: "gitlab-token",
    kind: "positive",
    support: "supported",
    input: values.gitlab,
    expected: one(values.gitlab, values.gitlab, {
      detector: "gitlab-token", type: "gitlab_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A documented GitLab token prefix with a substantial synthetic suffix is supported.",
  },
  {
    id: "gitlab-negative-common-identifier",
    detector: "gitlab-token",
    kind: "negative",
    support: "supported",
    input: "gitlab-project-identifier-00009",
    expected: [],
    note: "An ordinary GitLab-related identifier has no credential prefix.",
  },
  {
    id: "gitlab-boundary-custom-prefix",
    detector: "gitlab-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "custompat-SYNTHETIC_REVOKED_GITLAB_TOKEN",
    expected: [],
    note: "Administrator-customized personal access token prefixes are deliberately excluded.",
  },
  {
    id: "gitlab-overlap-context",
    detector: "gitlab-token",
    kind: "overlap",
    support: "supported",
    input: gitlabOverlap,
    expected: one(gitlabOverlap, values.gitlab, {
      detector: "gitlab-token", type: "gitlab_token", confidence: "high",
      specificity: "provider",
    }),
    note: "Documented provider evidence wins over an access-token assignment.",
  },
  {
    id: "gitlab-adversarial-long-suffix",
    detector: "gitlab-token",
    kind: "adversarial",
    support: "supported",
    input: `glpat-${"SYNTHETIC_REVOKED_".repeat(6_250)}!`,
    expected: one(`glpat-${"SYNTHETIC_REVOKED_".repeat(6_250)}!`, `glpat-${"SYNTHETIC_REVOKED_".repeat(6_250)}`, {
      detector: "gitlab-token", type: "gitlab_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A long delimited provider match remains deterministic and bounded.",
  },
  {
    id: "openai-positive-project",
    detector: "openai-token",
    kind: "positive",
    support: "supported",
    input: values.openai,
    expected: one(values.openai, values.openai, {
      detector: "openai-token", type: "openai_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "The recognized project-key shape is supported.",
  },
  {
    id: "openai-negative-model-name",
    detector: "openai-token",
    kind: "negative",
    support: "supported",
    input: "gpt-5.6-codex-2026-08-30",
    expected: [],
    note: "Model names are not API keys.",
  },
  {
    id: "openai-boundary-short",
    detector: "openai-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "sk-proj-short-example",
    expected: [],
    note: "Short documentation values are deliberately ignored.",
  },
  {
    id: "openai-overlap-context",
    detector: "openai-token",
    kind: "overlap",
    support: "supported",
    input: openAiOverlap,
    expected: one(openAiOverlap, values.openai, {
      detector: "openai-token", type: "openai_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "Provider evidence wins over a client-secret assignment.",
  },
  {
    id: "openai-adversarial-long-suffix",
    detector: "openai-token",
    kind: "adversarial",
    support: "supported",
    input: `sk-proj-${"A".repeat(100_000)}!`,
    expected: one(`sk-proj-${"A".repeat(100_000)}!`, `sk-proj-${"A".repeat(100_000)}`, {
      detector: "openai-token", type: "openai_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "A long delimited match remains deterministic and bounded.",
  },
  {
    id: "anthropic-positive-versioned",
    detector: "anthropic-token",
    kind: "positive",
    support: "supported",
    input: values.anthropic,
    expected: one(values.anthropic, values.anthropic, {
      detector: "anthropic-token", type: "anthropic_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "The versioned Anthropic namespace is owned by the Anthropic detector.",
  },
  {
    id: "anthropic-negative-unrelated-id",
    detector: "anthropic-token",
    kind: "negative",
    support: "supported",
    input: "SYNTHETIC_ANTHROPIC_DOCUMENTATION_ID",
    expected: [],
    note: "Unprefixed documentation identifiers are excluded.",
  },
  {
    id: "anthropic-boundary-version",
    detector: "anthropic-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "sk-ant-api02-SYNTHETIC_REVOKED_ANTHROPIC_KEY",
    expected: [],
    note: "Unknown Anthropic versions are not reclassified as OpenAI credentials.",
  },
  {
    id: "anthropic-overlap-context",
    detector: "anthropic-token",
    kind: "overlap",
    support: "supported",
    input: anthropicOverlap,
    expected: one(anthropicOverlap, values.anthropic, {
      detector: "anthropic-token", type: "anthropic_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "Anthropic provider evidence wins over the contextual assignment.",
  },
  {
    id: "anthropic-adversarial-long-suffix",
    detector: "anthropic-token",
    kind: "adversarial",
    support: "supported",
    input: `sk-ant-api03-${"A".repeat(100_000)}!`,
    expected: one(`sk-ant-api03-${"A".repeat(100_000)}!`, `sk-ant-api03-${"A".repeat(100_000)}`, {
      detector: "anthropic-token", type: "anthropic_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "A long delimited provider match remains deterministic and bounded.",
  },
  {
    id: "shopify-positive-admin-access",
    detector: "shopify-token",
    kind: "positive",
    support: "supported",
    input: values.shopify,
    expected: one(values.shopify, values.shopify, {
      detector: "shopify-token", type: "shopify_access_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A documented Shopify Admin API access-token prefix is supported.",
  },
  {
    id: "shopify-negative-header-name",
    detector: "shopify-token",
    kind: "negative",
    support: "supported",
    input: "X-Shopify-Access-Token",
    expected: [],
    note: "The access-token header name is not itself a credential.",
  },
  {
    id: "shopify-boundary-short",
    detector: "shopify-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "shpat_SYNTHETIC_SHORT",
    expected: [],
    note: "Short examples are ignored because Shopify documents the suffix as opaque.",
  },
  {
    id: "shopify-overlap-context",
    detector: "shopify-token",
    kind: "overlap",
    support: "supported",
    input: shopifyOverlap,
    expected: one(shopifyOverlap, values.shopify, {
      detector: "shopify-token", type: "shopify_access_token", confidence: "high",
      specificity: "provider",
    }),
    note: "Documented provider evidence wins over an access-token assignment.",
  },
  {
    id: "shopify-adversarial-long-suffix",
    detector: "shopify-token",
    kind: "adversarial",
    support: "supported",
    input: `shpat_${"SYNTHETIC_REVOKED_".repeat(6_250)}!`,
    expected: one(`shpat_${"SYNTHETIC_REVOKED_".repeat(6_250)}!`, `shpat_${"SYNTHETIC_REVOKED_".repeat(6_250)}`, {
      detector: "shopify-token", type: "shopify_access_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A long delimited provider match remains deterministic and bounded.",
  },
  {
    id: "vault-positive-service-token",
    detector: "vault-token",
    kind: "positive",
    support: "supported",
    input: values.vault,
    expected: one(values.vault, values.vault, {
      detector: "vault-token", type: "vault_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A modern Vault service-token prefix and documented minimum suffix are supported.",
  },
  {
    id: "vault-negative-common-identifier",
    detector: "vault-token",
    kind: "negative",
    support: "supported",
    input: "vault-service-identifier-00009",
    expected: [],
    note: "An ordinary Vault-related identifier has no modern token prefix.",
  },
  {
    id: "vault-boundary-legacy-prefix",
    detector: "vault-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "s.SYNTHETIC_REVOKED_LEGACY_VAULT_TOKEN",
    expected: [],
    note: "The collision-prone legacy one-letter prefix is deliberately excluded.",
  },
  {
    id: "vault-overlap-context",
    detector: "vault-token",
    kind: "overlap",
    support: "supported",
    input: vaultOverlap,
    expected: one(vaultOverlap, values.vault, {
      detector: "vault-token", type: "vault_token", confidence: "high",
      specificity: "provider",
    }),
    note: "Modern provider evidence wins over a client-secret assignment.",
  },
  {
    id: "vault-adversarial-long-suffix",
    detector: "vault-token",
    kind: "adversarial",
    support: "supported",
    input: `hvs.${"SYNTHETIC_REVOKED_".repeat(6_250)}!`,
    expected: one(`hvs.${"SYNTHETIC_REVOKED_".repeat(6_250)}!`, `hvs.${"SYNTHETIC_REVOKED_".repeat(6_250)}`, {
      detector: "vault-token", type: "vault_token", confidence: "high",
      specificity: "provider",
    }),
    note: "A long delimited provider match remains deterministic and bounded.",
  },
  {
    id: "jwt-positive-structured",
    detector: "jwt",
    kind: "positive",
    support: "supported",
    input: values.jwt,
    expected: one(values.jwt, values.jwt, {
      detector: "jwt", type: "jwt", confidence: "high", specificity: "structural",
    }),
    note: "A three-segment encoded-object shape is supported.",
  },
  {
    id: "jwt-negative-dotted-id",
    detector: "jwt",
    kind: "negative",
    support: "supported",
    input: "header.payload.signature",
    expected: [],
    note: "Arbitrary dotted identifiers are excluded.",
  },
  {
    id: "jwt-boundary-short-signature",
    detector: "jwt",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "eyJTWU5USEVU.eyJTWU5USEVU.short",
    expected: [],
    note: "Short signatures are deliberately ignored.",
  },
  {
    id: "jwt-overlap-bearer",
    detector: "jwt",
    kind: "overlap",
    support: "supported",
    input: jwtOverlap,
    expected: one(jwtOverlap, values.jwt, {
      detector: "jwt", type: "jwt", confidence: "high", specificity: "structural",
    }),
    note: "Registry order deterministically selects JWT over Bearer.",
  },
  {
    id: "jwt-adversarial-incomplete",
    detector: "jwt",
    kind: "adversarial",
    support: "supported",
    input: `eyJ${"A".repeat(100_000)}.missing`,
    expected: [],
    note: "A long incomplete shape terminates without a finding.",
  },
  {
    id: "bearer-positive-scheme",
    detector: "bearer-token",
    kind: "positive",
    support: "supported",
    input: `Bearer ${values.bearer}`,
    expected: one(`Bearer ${values.bearer}`, values.bearer, {
      detector: "bearer-token", type: "bearer_token", confidence: "high",
      specificity: "structural",
    }),
    note: "An explicit Bearer scheme is supported.",
  },
  {
    id: "bearer-negative-identifier",
    detector: "bearer-token",
    kind: "negative",
    support: "supported",
    input: "notbearer SYNTHETIC_REVOKED_IDENTIFIER",
    expected: [],
    note: "Bearer text embedded in an identifier is excluded.",
  },
  {
    id: "bearer-boundary-short",
    detector: "bearer-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "Bearer short-token",
    expected: [],
    note: "Short development tokens are deliberately ignored.",
  },
  {
    id: "bearer-overlap-jwt",
    detector: "bearer-token",
    kind: "overlap",
    support: "supported",
    input: jwtOverlap,
    expected: one(jwtOverlap, values.jwt, {
      detector: "jwt", type: "jwt", confidence: "high", specificity: "structural",
    }),
    note: "A structured JWT displaces the broader Bearer candidate.",
  },
  {
    id: "bearer-adversarial-punctuation",
    detector: "bearer-token",
    kind: "adversarial",
    support: "supported",
    input: `Bearer ${"!".repeat(100_000)}`,
    expected: [],
    note: "A long invalid alphabet terminates without a finding.",
  },
  {
    id: "connection-positive-postgres",
    detector: "connection-string",
    kind: "positive",
    support: "supported",
    input: `postgres://fixture:${values.connectionPassword}@localhost/db`,
    expected: one(`postgres://fixture:${values.connectionPassword}@localhost/db`, values.connectionPassword, {
      detector: "connection-string", type: "connection_string_password",
      confidence: "high", specificity: "structural",
    }),
    note: "Only the password in a supported authority is selected.",
  },
  {
    id: "connection-positive-encoded-ipv6",
    detector: "connection-string",
    kind: "positive",
    support: "supported",
    input: `😀 mongodb://fixture%3Auser:${values.encodedConnectionPassword}@[2001:db8::1]:27017/db`,
    expected: one(
      `😀 mongodb://fixture%3Auser:${values.encodedConnectionPassword}@[2001:db8::1]:27017/db`,
      values.encodedConnectionPassword,
      {
        detector: "connection-string", type: "connection_string_password",
        confidence: "high", specificity: "structural",
      },
    ),
    note: "Encoded delimiters retain original UTF-16 offsets beside Unicode text and an IPv6 host.",
  },
  {
    id: "connection-positive-port",
    detector: "connection-string",
    kind: "positive",
    support: "supported",
    input: `mysql://fixture:${values.connectionPassword}@db.example.test:3306/db`,
    expected: one(
      `mysql://fixture:${values.connectionPassword}@db.example.test:3306/db`,
      values.connectionPassword,
      {
        detector: "connection-string", type: "connection_string_password",
        confidence: "high", specificity: "structural",
      },
    ),
    note: "A numeric port on a valid host preserves the bounded password span.",
  },
  {
    id: "connection-negative-host-only",
    detector: "connection-string",
    kind: "negative",
    support: "supported",
    input: "postgres://localhost/example",
    expected: [],
    note: "Host-only URLs contain no credential.",
  },
  {
    id: "connection-boundary-placeholder",
    detector: "connection-string",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "postgres://fixture:password@localhost/example",
    expected: [],
    note: "Obvious placeholders are deliberately ignored.",
  },
  {
    id: "connection-boundary-missing-password",
    detector: "connection-string",
    kind: "boundary",
    support: "supported",
    input: "postgres://fixture:@localhost/example",
    expected: [],
    note: "Empty password userinfo is credential-free.",
  },
  {
    id: "connection-negative-malformed-percent",
    detector: "connection-string",
    kind: "negative",
    support: "supported",
    input: "postgres://fixture:SYNTHETIC%GGREVOKED@localhost/example",
    expected: [],
    note: "Malformed percent escapes invalidate the userinfo authority.",
  },
  {
    id: "connection-overlap-context",
    detector: "connection-string",
    kind: "overlap",
    support: "supported",
    input: connectionOverlap,
    expected: one(connectionOverlap, values.connectionPassword, {
      detector: "connection-string", type: "connection_string_password",
      confidence: "high", specificity: "structural",
    }),
    note: "The bounded password displaces the wider contextual value.",
  },
  {
    id: "connection-adversarial-overlong",
    detector: "connection-string",
    kind: "adversarial",
    support: "supported",
    input: `postgres://fixture:${"A".repeat(100_000)}@localhost/db`,
    expected: [],
    note: "An overlong password is ignored in bounded time.",
  },
  {
    id: "connection-adversarial-malformed-authority",
    detector: "connection-string",
    kind: "adversarial",
    support: "supported",
    input: `postgres://fixture:${"%2".repeat(50_000)}@localhost/db`,
    expected: [],
    note: "An overlong malformed authority is abandoned after a fixed scan bound.",
  },
  {
    id: "contextual-positive-assignment",
    detector: "generic-token",
    kind: "positive",
    support: "supported",
    input: `api_key=${values.contextual}`,
    expected: one(`api_key=${values.contextual}`, values.contextual, {
      detector: "generic-token", type: "contextual_secret", confidence: "high",
      specificity: "contextual",
    }),
    note: "A high-signal assignment with bounded entropy is supported.",
  },
  {
    id: "contextual-negative-token-name",
    detector: "generic-token",
    kind: "negative",
    support: "supported",
    input: `token=${values.contextual}`,
    expected: [],
    note: "The generic token name is an explicit exclusion.",
  },
  {
    id: "contextual-boundary-short",
    detector: "generic-token",
    kind: "boundary",
    support: "intentionally-unsupported",
    input: "api_key=abcdefg",
    expected: [],
    note: "Values below the minimum length are deliberately ignored.",
  },
  {
    id: "contextual-overlap-provider",
    detector: "generic-token",
    kind: "overlap",
    support: "supported",
    input: openAiOverlap,
    expected: one(openAiOverlap, values.openai, {
      detector: "openai-token", type: "openai_api_key", confidence: "high",
      specificity: "provider",
    }),
    note: "The contextual candidate yields to provider specificity.",
  },
  {
    id: "contextual-adversarial-overlong",
    detector: "generic-token",
    kind: "adversarial",
    support: "supported",
    input: `api_key=${"A".repeat(100_000)}`,
    expected: [],
    note: "A value above the detector bound is ignored deterministically.",
  },
  {
    id: "future-provider-family-pending",
    detector: "unassigned",
    kind: "boundary",
    support: "not-yet-evaluated",
    input: "future_provider_SYNTHETIC_REVOKED_UNQUALIFIED_VALUE",
    expected: null,
    note: "Unqualified provider families require evidence before expectations are set.",
  },
] as const;
