/**
 * Deterministic, pure generator for scale workload profile inputs
 * (`fixtures/workload-profiles.json`, `purpose: "scale"`). It reads and
 * writes nothing: the same profile always produces the same byte-for-byte
 * output, so a workload input is reproduced from its profile rather than
 * committed as a multi-megabyte fixture. `schema.test.ts` proves this
 * determinism and inspects every generated input's size before any
 * consumer runs it.
 *
 * Every generated byte comes from one of the constant filler lines or the
 * one constant synthetic secret line below — there is no randomness and no
 * way for this generator to emit anything other than unmistakably synthetic
 * text.
 */

import type { AssessmentCategory, AssessmentWorkloadProfile } from "./schema.js";

/** Identifies this exact generator function; profiles pin their algorithm. */
export const GENERATOR_ALGORITHM = "assessment-filler-density-v1";

const CATEGORY_FILLER: Record<AssessmentCategory, string> = {
  logs: "2026-09-12T00:00:00Z INFO fixture request completed status=200 latency_ms=12\n",
  code: "function computeFixtureTotal(values) {\n  return values.reduce((a, b) => a + b, 0);\n}\n",
  chat: "Hey, did you get a chance to look at the fixture PR yet? No rush.\n",
  "negative-text": "The quick brown fox jumps over the lazy dog near the old fixture barn.\n",
};

const CATEGORY_UNICODE_FILLER: Record<AssessmentCategory, string> = {
  logs: "2026-09-12T00:00:00Z ｲﾝﾌｫ 요청 완료 상태=200 café=\u{1F511}\n",
  code: "// función de prueba: サンプル \u{1F600}\n",
  chat: "¡Hola! ¿Cómo estás? 你好吗？ \u{1F600}\n",
  "negative-text": "Café naïve résumé \u{1F98A} über den alten Zaun.\n",
};

/** Obviously synthetic and revoked; matches no real credential format. */
const SYNTHETIC_SECRET_LINE =
  "token=ghp_ASSESSMENTSYNTHETIC0000000000000000\n";

const encoder = new TextEncoder();

function utf8ByteLength(input: string): number {
  return encoder.encode(input).length;
}

/**
 * Generates `profile.targetInputBytes` (to the nearest whole filler or
 * secret line) of synthetic text: filler lines drawn from the profile's
 * category, with a `token=ghp_ASSESSMENTSYNTHETIC...`-shaped synthetic
 * secret line inserted every N lines to approximate `targetDensityPerKiB`.
 * `unicodeMix` swaps in the category's non-ASCII filler variant.
 *
 * Pure function of `profile`'s fields alone: no I/O, no clock, no random
 * source. The same profile always returns the same string.
 */
export function generateWorkloadInput(profile: AssessmentWorkloadProfile): string {
  const filler = profile.unicodeMix
    ? CATEGORY_UNICODE_FILLER[profile.category]
    : CATEGORY_FILLER[profile.category];
  const fillerBytes = utf8ByteLength(filler);
  const secretBytes = utf8ByteLength(SYNTHETIC_SECRET_LINE);
  const linesPerKiB = 1024 / fillerBytes;
  const secretEveryNLines = profile.targetDensityPerKiB > 0
    ? Math.max(1, Math.round(linesPerKiB / profile.targetDensityPerKiB))
    : Number.POSITIVE_INFINITY;

  const lines: string[] = [];
  let bytes = 0;
  let line = 0;
  while (bytes < profile.targetInputBytes) {
    line += 1;
    const useSecret = Number.isFinite(secretEveryNLines) &&
      line % secretEveryNLines === 0;
    lines.push(useSecret ? SYNTHETIC_SECRET_LINE : filler);
    bytes += useSecret ? secretBytes : fillerBytes;
  }
  return lines.join("");
}
